[package]
name = "promptly"
version = "0.1.0"
authors = ["Jason Ross <jasonross1024@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
unicode-segmentation = "1.7.1"
